[package]
name = "sbe-sample-app"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8"

spot_sbe = { path = "../spot_sbe" }
